// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Serilog.Events;
using System;
using System.Collections.Generic;
using SqlServerSink.Models;

namespace CombinedConfigDemo.Models;

public partial class LogEvents
{
    public int Id { get; set; }
    public string Message { get; set; }
    public string Level { get; set; }
    public DateTime? Timestamp { get; set; }
    public string Exception { get; set; }
    public LogEntry LogEvent { get; set; }

}