// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using SerilogCurrentFileNameSample.Classes.Interceptors;
using SerilogCurrentFileNameSample.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace SerilogCurrentFileNameSample.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BirthDay> BirthDays { get; set; }

    /// <summary>
    /// Configures the database context options, including the connection string, 
    /// logging, and interceptors.
    /// </summary>
    /// <param name="optionsBuilder">
    /// The builder used to configure the database context options.
    /// </param>
    /// <remarks>
    /// This method sets up the SQL Server connection using the main connection string 
    /// from AppConnections.Instance.MainConnection. It also enables 
    /// sensitive data logging, adds an <see cref="AuditInterceptor"/> for auditing 
    /// database changes, and configures logging to output messages to the debug window.
    /// </remarks>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(AppConnections.Instance.MainConnection)
            .EnableSensitiveDataLogging()
            .AddInterceptors(new AuditInterceptor())
            .LogTo(message => Debug.WriteLine(message));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BirthDay>(entity =>
        {
            entity.Property(e => e.YearsOld).HasComputedColumnSql("((CONVERT([int],format(getdate(),'yyyyMMdd'))-CONVERT([int],format([BirthDate],'yyyyMMdd')))/(10000))", false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}