// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using EF_Core1.Models;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EF_Core1.Data;

public partial class Context : DbContext
{

    public Context(DbContextOptions<Context> options) : base(options)
    {
    }

    public virtual DbSet<ContactType> ContactType { get; set; }

    public virtual DbSet<Contacts> Contacts { get; set; }

    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ContactTypeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ContactsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CountriesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CustomersConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
